### ISSUE TITLE
Nachrichten-Feeds suchen und abonnieren

### ISSUE THREAD

**Issue by krieger2501** [wwi21seb-projekt/server-alpha#3]
ID 8 - Als Nutzer möchte ich die Möglichkeit haben, andere Nutzer zu suchen und ihre persönlichen Nachrichten-Feeds anzeigen zu können und zu abonnieren

**Comment by trashstackdev** [comment]
Mein Aufwand: 6 Studenten

**Comment by abramsmax** [comment]
Mein Aufwand: 10 Stunden

**Comment by NilsAbels** [comment]
Mein Aufwand: 3 Stunden
